version: 3
endpoint: https://charity-api.fullstacksjs.com/
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
